spring.application.name=demo

server.port=8080
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://ep-delicate-dawn-ad3tswwx-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_UMV8yf0JWYXh
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

ia.service.url=http://localhost:8000

logging.level.com.supermercado=DEBUG
logging.level.org.springframework=INFO
